application: udacity-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css  
- url: /fonts
  static_dir: static/fonts  
- url: /img
  static_dir: static/img 
- url: /js
  static_dir: static/js
- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"